### ISSUE TITLE
Publish "official" v1 of The OVAL Community Guidelines

### ISSUE THREAD

**Issue by adammontville** [CISecurity/oval-governance-update#60]
Documentation for the OVAL Community is found [here](http://oval-community-guidelines.readthedocs.io/en/latest/index.html). That documentation needs to be completed, and this epic creates a bucket for those things that need doing.

**Comment by zport** [comment]
- [ ] #59 _collect further actions_
- [ ] #58 _copyright statement_
- [ ] #29 _issue creation mechanics_
- [ ] #24 _pull request mechanics_
- [ ] #22 _release process mechanics_
